# docker-compose.base.yml
services:
  base: # name of this service, will be used in basecontainer.json
    image: ros2_base # the image will have this name once built
    build:
      context: .
      dockerfile: Dockerfile # the only dockerfile
      args:
        ROS_DISTRO: jazzy 
      target: ros2_base # must match the stage name in Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=xcb
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all  # Grants all NVIDIA driver capabilities to the container
      - NVIDIA_VISIBLE_DEVICES=all      # Makes all NVIDIA devices visible to the container
      - ROS_DOMAIN_ID=42                # override default domain ID for ros nodes
      #- __NV_PRIME_RENDER_OFFLOAD=1 # Enables NVIDIA PRIME render offload
      #- __GLX_VENDOR_LIBRARY_NAME=nvidia # Specifies the GLX vendor library to use (NVIDIA)
    command: bash